"use client";

import React, { useCallback, useEffect, useState } from "react";
import { AlertTriangle, RefreshCw, WifiOff, Loader2, Sparkle } from "lucide-react";

/**
 * ApiStatusBanner — reusable retry + status banner for failure states.
 *
 * Variants:
 *  - "error"       : API/unexpected failure with a Retry button
 *  - "ocr-failed"  : scan processing failed, with a Retry Scan action
 *  - "offline"     : navigator.onLine is false — shown globally in layout
 *
 * All colors come from the app's CSS variables so it matches the design system.
 */

const VARIANTS = {
  error: {
    bg: "var(--error-light)",
    border: "rgba(239, 68, 68, 0.3)",
    color: "var(--error-text)",
    icon: AlertTriangle,
  },
  "ocr-failed": {
    bg: "var(--error-light)",
    border: "rgba(239, 68, 68, 0.3)",
    color: "var(--error-text)",
    icon: AlertTriangle,
  },
  offline: {
    bg: "var(--warning-light)",
    border: "rgba(245, 158, 11, 0.3)",
    color: "var(--warning-text)",
    icon: WifiOff,
  },
};

export default function ApiStatusBanner({
  variant = "error",
  title,
  message,
  retryLabel = "Retry",
  onRetry,
  retrying = false,
  className = "",
}) {
  const v = VARIANTS[variant] || VARIANTS.error;
  const Icon = v.icon;
  const [online, setOnline] = useState(true);

  // Offline detection only matters for the offline variant; keeps the others static.
  useEffect(() => {
    if (variant !== "offline") return;
    const update = () => setOnline(navigator.onLine);
    update();
    window.addEventListener("online", update);
    window.addEventListener("offline", update);
    return () => {
      window.removeEventListener("online", update);
      window.removeEventListener("offline", update);
    };
  }, [variant]);

  const handleRetry = useCallback(() => {
    if (onRetry && !retrying) onRetry();
  }, [onRetry, retrying]);

  const isOffline = variant === "offline" && !online;

  return (
    <div
      className={`flex items-center justify-between gap-3 px-4 py-3.5 rounded-2xl animate-fade-in ${className}`}
      style={{ background: v.bg, border: `1.5px solid ${v.border}` }}
      role={variant === "offline" ? "status" : "alert"}
    >
      <div className="flex items-center gap-3 min-w-0">
        <Icon size={20} className="flex-shrink-0" style={{ color: v.color }} />
        <div className="min-w-0">
          <p className="text-sm font-bold leading-tight" style={{ color: v.color }}>
            {title || (variant === "offline" ? "You're offline" : "Something went wrong")}
          </p>
          {message && (
            <p className="text-sm font-medium mt-0.5 truncate" style={{ color: "var(--text-3)" }}>
              {message}
            </p>
          )}
        </div>
      </div>

      {onRetry && variant !== "offline" && (
        <button
          onClick={handleRetry}
          disabled={retrying || (variant === "offline" && isOffline)}
          className="btn btn-danger btn-sm font-bold flex-shrink-0 cursor-pointer flex items-center gap-1.5"
        >
          {retrying ? (
            <>
              <Loader2 size={14} className="animate-spin" />
              <span>Retrying…</span>
            </>
          ) : (
            <>
              <RefreshCw size={14} />
              <span>{retryLabel}</span>
            </>
          )}
        </button>
      )}
    </div>
  );
}

/**
 * AiEngineChip — small transparency badge showing which AI model produced a
 * given output (e.g. "gemini-2.0-flash" / "qwen2.5vl:7b"). Renders nothing
 * when no engine label is available.
 */
export function AiEngineChip({ engine }) {
  if (!engine) return null;
  const short = String(engine).split(":").pop(); // "gemini:gemini-2.0-flash" → "gemini-2.0-flash"
  return (
    <span
      className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-extrabold uppercase tracking-wide"
      style={{
        background: "rgba(20,184,166,0.1)",
        color: "var(--primary-dark, #0F766E)",
        border: "1px solid rgba(20,184,166,0.25)",
      }}
      title={`AI output generated by ${engine}`}
    >
      <Sparkle size={10} />
      {short}
    </span>
  );
}

/** Convenience wrapper: global offline banner for the root layout. */
export function GlobalOfflineBanner() {
  const [offline, setOffline] = useState(false);

  useEffect(() => {
    const update = () => setOffline(!navigator.onLine);
    update();
    window.addEventListener("online", update);
    window.addEventListener("offline", update);
    return () => {
      window.removeEventListener("online", update);
      window.removeEventListener("offline", update);
    };
  }, []);

  if (!offline) return null;
  return (
    <div className="sticky top-0 z-50 px-4 pt-2">
      <ApiStatusBanner
        variant="offline"
        title="You're offline — changes may not save"
        message="Scans are queued locally and will sync when the connection returns."
      />
    </div>
  );
}
